export default ['animal','pig','dog','cat','wing','hippopotamus','goat','deer','giraffe','elephant','lion','leopard','fox','wolf','wolf-down','rabbit','monkey','gorilla','koala','hedgehog','camel','kangaroo','horse','bird','mouse','cow',
'transportation','train','plane','car','truck','bicycle','bike','bus','boat','ship','tire','gasoline','engine','ticket','streetcar','tramcar','trolleybus','conductor','inspector','railway','track','carriage','dining-car','platform','canteen','buffet','waiting-room','registration','disembark','take-off',
'location','house','apartment','street','airport','station','bridge','restaurant','farm','court','town','university','club','bar','park','camp','theater','library','hospital','church','market','country','building','ground','space','bank',
'drugstore','department','department-store','museum','fairground','post-office','cinema','art-gallery','government','shipside','toilet','tower','temple','dormitory','dentist','study','castle','laundromat','botanic-garden',
'clothing','dress','suit','skirt','shirt','pants','shoes','porket','coat','stain','color','brown','gray','white','person','daughter','husband','wife','king','queen','president','neighbor','adult','human','victim','crowd',
,'job','doctor','patient','secretary','priest','police','army','soldier','artist','auther','manager','reporter','actor','soclity','religion','heaven','hell','medicien','money','doller','bill','marriage','wedding','team','ethnicity','sex','murder'
,'prison','technology','enargy','war','peace','attack','election','magazine','gun','sport','race','exercise','ball','game','price','contract','proson','sign','science','god','art','song','band','musical','instruments','movie','drink','coffee','wine','beer','juice','water','milk',
'food','cheese','bread','soup','cake','chicken','pork','beef','apple','banana','orange','lemon','corn','rice','oil','seed','knife','Spoon','fork','plate','cap','breakfast','lunch','dinner','sugar','salt','bottle','home','desk','chair','bed','dream','window','door','bedroom','kitchen','bathroom','pencil','pen','photograph','soap','paint'
,'letter','note','wall','paper','floor','ceiling','roof','pool','lock','telephone','garden','yard','needle','bag','box','gift','card','ring','tool','electronics','lock','lamp','fan','cell,phone','network','program','laptop','screen','camera','television',
'nature','sea','ocean','river','mountain','rain','tree','sun','moon','world','earth','forest','sky','plant','wind','soil','flower','valley','root','lake','star','grass','leaf','air','send','beach','wave','fire','ice','island','hill','heat','materils','metal','plastic','stone','diamond','clay','dust','gold','copper','silver',
'math','measurement','meter','centimeter','kilogram','inch','foot','pound','half','circle','squere','temperature','weight','corner','eage','the,nouns','dot','consonant','vowel','light','sound','piece','pain','injury','hole','pattern','direction','front','up','straight',
'north','south','east','west','season','spring','summer','fall','winter','month','january','february','marth','april','may','june','july','august','september','october','november','december',
'three','eleven','twelve','thirteen','fifteen','twenty','thirty','forty','fifty','hundred','monday','tuesday','wednesday','thursday','friday','saturday','sunday','hour','minute','second','morning','afternoon','evening','night',
'the-verbs','work','walk','run','drive','fly','swin','follow','think','speak','say','kill','die','smile','laugh','cry','play','mell','learn','jump','smell','hear-voice-sound','listen','taste','touch','burn','melt','dig','explode','sit','stand','pass-bay','cut','fight','lie-down','dance','sleep',
'wake-up','sing','count','marry','pray','win','lose','mix/stir','bend','wash','cook','write','call','build','teach','grow','draw','feed','catch','throw','clean','find','fall','push','pull','carry','break','wear','hang','shake','sign','beat','lift',
'adjective','tall','short','narrow','big','small/little','slow','fast','hot','cold','warm','cool','old','young','bad','wet','dry','sick','healthy','loud','queit','happy','sad','beautiful','ugly','deaf-mute','blind','nice','mean','rich','poor','thick','thin','expensive','cheap','flat',
'curved','male','female','Tight','Loose','height','low','Soft','Hard','Deep','Shallow','Clean','Dirty','Strong','Weak','Dead','Alive','Heavy','Light','Dark','Nuclear','Famous'
]
