export default ['animal','pig','dog','cat','wing','hurse','bird','mouse','cow','horse','transportation','train','plane','car','truck','bicycle','bike','bus','boat','ship','tire','gasoline','engine','ticket','location','house','apartment','street',
,'airport','train','station','bridge','restaurant','farm','court','town','university','club','bar','park','camp','theater','library','hospital','church','market','country','building','ground','space','bank',
,'clothing','dress','suit','skirt','shirt','pants','shoes','porket','coat','stain','color','brown','gray','white',,'person','daughtor','husband','wife','king','queen','president','neighbor','adult','human','victim','crowd',
,'job','doctor','patient','secretary','priest','police','army','soldier','artist','auther','manager','reporter','actor','soclity','religion','heaven','hell','medicien','money','doller','bill','marriage','wedding','team','ethnicity','sex','murder'
,'prison','technology','enargy','war','peace','attack','election','magazine','gun','sport','race','exercise','ball','game','price','contract','proson','sign','science','god','art','song','band','musical','instruments','movie','drink','coffee','wine','beer','juice','water','milk',
'food','cheese','bread','soup','cake','chicken','pork','beef','apple','banana','orange','lemon','corn','rice','oil','seed','knife','Spoon','fork','plate','cap','breakfast','lunch','dinner','sugar','salt','bottle','home','desk','chair','bed','dream','window','door','bedroom','kitchen','bathroom','pencil','pen','photograph','soap','paint'
,'letter','note','wall','paper','floor','ceiling','roof','pool','lock','telephone','garden','yard','needle','bag','box','gift','card','ring','tool','electronics','lock','lamp','fan','cell phone','network','program','laptop','screen','camera','television',
'nature','sea','ocean','river','mountain','rain','tree','sun','moon','world','earth','forest','sky','plant','wind','soil','flower','valley','root','lake','star','grass','leaf','air','send','beach','wave','fire','ice','island','hill','heat','materils','matel','plastic','stone','diamond','clay','dust','gold','copper','silver',
'math','measurement','meter','centimeter','kilogram','inch','foot','pound','half','circle','squere','temperature','weight','corner','eage','the nouns','dot','consonant','vowel','light','sound','piece','pain','injury','hole','pattern','direction','front','up','straight','north','south','east','west','season','spring','summer','fall','winter','month','january','february','marth','april','may','june','july','august','september','october','november','december'
]
    