export default ['动物','马','牛','老鼠','翅膀','鸟','交通','火车','卡车','自行车','小艇','船','轮胎','汽油','引擎','地点','公寓','街道','机场','餐厅','农村','法院','城镇','大学','俱乐部','酒吧','公园','营地','剧院','图书馆','医院','教堂','市场','国家','建筑','地面','太空','银行',
'服装','帽子','连衣裙','西装','裙子','衬衫','裤子','鞋子','口袋','外套','污渍','棕色','灰色','白色','人物','女儿','丈夫','妻子','国王','女王','总统','邻居','成人','人类','受害者','人群','律师','医生','病人','秘书','牧师','军队','军人','艺术家','作者','经理','记者','演员',
'社会','宗教','天堂','地狱','死亡','医学','金钱','美元','账单','婚姻','婚礼','团队','种族','性行为','谋杀','监狱','科技，技术','能源','战争','毒药','和平，平静','攻击','选举','杂志，弹药库','枪','体育','赛跑','运动','球','游戏','价格','合同','毒品','迹象','科学','上帝'
,'艺术','乐队','歌曲','乐器','饮料','咖啡','茶','葡萄酒','啤酒','果汁','水','牛奶',,'食物','奶酪','面包','汤','蛋糕','鸡肉','猪肉','牛肉','玉米','大米','油','种子','刀','勺子','盘子','杯子','早餐','午餐','晚餐','食糖','盐','瓶子','家内','桌子','椅子',
'床','梦','窗口','门','卧室','厨房','浴室','铅笔','笔','相片','肥皂','油漆','信件','笔记','墙壁','纸张','地板','天花板','屋顶','游泳池','锁','电话','花园','院子','针','包','盒子','礼物','卡片','戒指','工具','电子产品','时钟','电灯','风扇','手机','网络','电脑程序','笔记本电脑','屏幕','照相机','电视剧',
'animal','pig','dog','cat','wing','hurse','bird','mouse','cow','horse','transportation','train','plane','car','truck','bicycle','bike','bus','boat','ship','tire','gasoline','engine','ticket','location','house','apartment','street',
,'airport','train','station','bridge','restaurant','farm','court','town','university','club','bar','park','camp','theater','library','hospital','church','market','country','building','ground','space','bank',
,'clothing','dress','suit','skirt','shirt','pants','shoes','porket','coat','stain','color','brown','gray','white',,'person','daughtor','husband','wife','king','queen','president','neighbor','adult','human','victim','crowd',
,'job','doctor','patient','secretary','priest','police','army','soldier','artist','auther','manager','reporter','actor','soclity','religion','heaven','hell','medicien','money','doller','bill','marriage','wedding','team','ethnicity','sex','murder'
,'prison','technology','enargy','war','peace','attack','election','magazine','gun','sport','race','exercise','ball','game','price','contract','proson','sign','science','god','art','song','band','musical','instruments','movie','drink','coffee','wine','beer','juice','water','milk',
'food','cheese','bread','soup','cake','chicken','pork','beef','apple','banana','orange','lemon','corn','rice','oil','seed','knife','Spoon','fork','plate','cap','breakfast','lunch','dinner','sugar','salt','bottle','home','desk','chair','bed','dream','window','door','bedroom','kitchen','bathroom','pencil','pen','photograph','soap','peint'
,'letter','note','wall','paper','floor','ceiling','roof','pool','lock','telephone','garden','yard','needle','bag','box','gift','card','ring','tool','electronics','lock','lamp','fan','cell phone','network','program','laptop','screen','camera','television'
]